
marsupilami_addresses_homepage:
    path:     /{page}
    defaults:  
        _controller: MarsupilamiInfosBundle:Infos:index
        page:        1
    requirements:
        page: \d*

marsupilami_addresses_view:
    path:     /advert/{id}
    defaults:
        _controller: MarsupilamiInfosBundle:Infos:view
    requirements:
        id: \d+

marsupilami_addresses_add:
    path:      /add
    defaults:
        _controller: MarsupilamiInfosBundle:Infos:add

marsupilami_addresses_edit:
    path:      /edit/{id}
    defaults:
        _controller: MarsupilamiInfosBundle:Infos:edit
    requirements:
        id: \d+

marsupilami_addresses_delete:
    path:      /delete/{id}
    defaults:
        _controller: MarsupilamiInfosBundle:Infos:delete
    requirements:
        id: \d+